service: f-project

frameworkVersion: "3"

plugins:
    - serverless-jetpack
    - serverless-offline

provider:
    name: aws
    runtime: nodejs20.x
    region: us-east-1
    httpApi:
        cors: true

functions:
    api:
        handler: dist/lambda.handler
        events:
            - httpApi:
                  method: any
                  path: /
            - httpApi:
                  method: any
                  path: /{proxy+}